apiVersion: apps/v1
kind: Deployment
metadata:
  name: nxjslbdys
spec:
  replicas: 1
  selector:
    matchLabels:
      app:nxjslbdys
  template:
    metadata:
      labels:
        app:nxjslbdys
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name:nxjslbdys
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4db43ec7-dae3-476a-b75a-ef64531ade91"
        - name: Vless_Path
          value: "/vlgnj55"
        - name: Vmess_UUID
          value: "4db43ec7-dae3-476a-b75a-ef64531ade91"
        - name: Vmess_Path
          value: "/vm6ygfr66"
        - name: Share_Path
          value: "/v2link"
